version: '3.8'

volumes:
  mongo:
  redis:

services: 
  wildduck:
    image: ghcr.io/zone-eu/wildduck:1.45.5
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "143:143"
      - "110:110"
    depends_on:
      - mongo
      - redis
    volumes:
      - ./config/wildduck:/wildduck/config
    environment:
      - NODE_ENV=production
      - HOSTNAME=${RAILWAY_PUBLIC_DOMAIN}

  wildduck-webmail:
    image: nodemailer/wildduck-webmail:latest
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - mongo
      - redis
      - wildduck
    volumes:
      - ./config/wildduck-webmail:/app/config
    environment:
      - NODE_ENV=production
      - HOSTNAME=${RAILWAY_PUBLIC_DOMAIN}

  zonemta:
    image: ghcr.io/zone-eu/zonemta-wildduck:1.32.20
    restart: unless-stopped
    ports:
      - "587:587"
    depends_on: 
      - mongo
      - redis
    volumes:
      - ./config/zone-mta:/app/config
    environment:
      - NODE_ENV=production
      - HOSTNAME=${RAILWAY_PUBLIC_DOMAIN}

  haraka:
    image: ghcr.io/zone-eu/haraka-plugin-wildduck:5.8.22
    restart: unless-stopped
    ports:
      - "25:25"
    depends_on:
      - mongo
      - redis
      - rspamd
    volumes:
      - ./config/haraka:/app/config
    environment:
      - NODE_ENV=production
      - HOSTNAME=${RAILWAY_PUBLIC_DOMAIN}

  rspamd:
    image: nodemailer/rspamd
    restart: unless-stopped
    depends_on:
      - redis
    volumes:
      - ./config/rspamd/override.d:/etc/rspamd/override.d
      - ./config/rspamd/worker-normal.conf:/etc/rspamd/worker-normal.conf
      - ./config/rspamd/local.d:/etc/rspamd/local.d

  mongo:
    image: mongo:5.0
    restart: unless-stopped
    volumes:
      - mongo:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME:-admin}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD:-password}
    
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    volumes:
      - redis:/data
    command: redis-server --requirepass ${REDIS_PASSWORD:-password}