[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile.railway"

[deploy]
startCommand = "./setup-railway.sh"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
healthcheckPath = "/health"
healthcheckTimeout = 300

[environments.production]
variables = { NODE_ENV = "production", PORT = "8080" }

[environments.staging]
variables = { NODE_ENV = "staging", PORT = "8080" }